package Producto;
/*
 * @author Hacktotopo
*/

public class Multiplicacion extends javax.swing.JFrame {
    public Multiplicacion() {
        initComponents();
        this.setLocationRelativeTo(null);        
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        General = new javax.swing.JPanel();
        GoBack = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Solved = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        APanel = new javax.swing.JPanel();
        AXI = new javax.swing.JTextField();
        AYJ = new javax.swing.JTextField();
        AZK = new javax.swing.JTextField();
        jlAXI = new javax.swing.JLabel();
        jlAYJ = new javax.swing.JLabel();
        jlAZK = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BPanel = new javax.swing.JPanel();
        GEscalar = new javax.swing.JTextField();
        jlEscalar = new javax.swing.JLabel();
        RVector = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        JLModulo = new javax.swing.JLabel();
        RModulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(550, 550));
        setResizable(false);

        General.setBackground(new java.awt.Color(44, 151, 222));
        General.setForeground(java.awt.Color.white);
        General.setPreferredSize(new java.awt.Dimension(550, 550));

        GoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Regresar.png"))); // NOI18N
        GoBack.setText("Regresar");
        GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackActionPerformed(evt);
            }
        });

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Reducir.png"))); // NOI18N
        Clear.setText("Limpiar");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Solved.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Resolver.png"))); // NOI18N
        Solved.setText("Resolver");
        Solved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolvedActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Titulo.setForeground(java.awt.Color.white);
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("MULTIPLICACIÓN VECTOR POR UN ESCALAR");

        APanel.setBackground(new java.awt.Color(43, 43, 43));
        APanel.setPreferredSize(new java.awt.Dimension(520, 120));

        AXI.setBackground(new java.awt.Color(119, 120, 123));
        AXI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AXI.setForeground(new java.awt.Color(236, 240, 241));
        AXI.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AYJ.setBackground(new java.awt.Color(119, 120, 123));
        AYJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AYJ.setForeground(new java.awt.Color(236, 240, 241));
        AYJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AZK.setBackground(new java.awt.Color(119, 120, 123));
        AZK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AZK.setForeground(new java.awt.Color(236, 240, 241));
        AZK.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlAXI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAXI.setForeground(new java.awt.Color(255, 196, 35));
        jlAXI.setText("AxI");

        jlAYJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAYJ.setForeground(new java.awt.Color(255, 196, 35));
        jlAYJ.setText("AyJ");

        jlAZK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAZK.setForeground(new java.awt.Color(255, 196, 35));
        jlAZK.setText("AzK");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 216, 0));
        jLabel1.setText("VECTOR");

        javax.swing.GroupLayout APanelLayout = new javax.swing.GroupLayout(APanel);
        APanel.setLayout(APanelLayout);
        APanelLayout.setHorizontalGroup(
            APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(APanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AXI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAXI))
                .addGap(18, 18, 18)
                .addGroup(APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jlAYJ)
                    .addComponent(AYJ, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AZK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAZK))
                .addContainerGap())
        );
        APanelLayout.setVerticalGroup(
            APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(APanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AXI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AYJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AZK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAXI)
                    .addComponent(jlAYJ)
                    .addComponent(jlAZK))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        BPanel.setBackground(new java.awt.Color(43, 43, 43));
        BPanel.setPreferredSize(new java.awt.Dimension(486, 92));

        GEscalar.setBackground(new java.awt.Color(119, 120, 123));
        GEscalar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GEscalar.setForeground(new java.awt.Color(236, 240, 241));
        GEscalar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlEscalar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEscalar.setForeground(new java.awt.Color(255, 216, 0));
        jlEscalar.setText("ESCALAR");

        javax.swing.GroupLayout BPanelLayout = new javax.swing.GroupLayout(BPanel);
        BPanel.setLayout(BPanelLayout);
        BPanelLayout.setHorizontalGroup(
            BPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEscalar)
                .addGap(18, 18, 18)
                .addComponent(GEscalar, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        BPanelLayout.setVerticalGroup(
            BPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(BPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEscalar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        RVector.setEditable(false);
        RVector.setBackground(new java.awt.Color(245, 80, 100));
        RVector.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RVector.setForeground(new java.awt.Color(236, 240, 241));
        RVector.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RVector.setText("RESULTADO");

        jPanel1.setBackground(new java.awt.Color(43, 43, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(486, 92));

        JLModulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLModulo.setForeground(new java.awt.Color(255, 216, 0));
        JLModulo.setText("MODULO");

        RModulo.setBackground(new java.awt.Color(119, 120, 123));
        RModulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RModulo.setForeground(new java.awt.Color(236, 240, 241));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLModulo)
                .addGap(18, 18, 18)
                .addComponent(RModulo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLModulo)
                    .addComponent(RModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout GeneralLayout = new javax.swing.GroupLayout(General);
        General.setLayout(GeneralLayout);
        GeneralLayout.setHorizontalGroup(
            GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(APanel, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralLayout.createSequentialGroup()
                .addGroup(GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GeneralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GeneralLayout.createSequentialGroup()
                        .addComponent(Solved, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GoBack)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralLayout.createSequentialGroup()
                        .addComponent(RVector, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)))
                .addContainerGap())
        );
        GeneralLayout.setVerticalGroup(
            GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(APanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RVector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Solved)
                    .addComponent(Clear)
                    .addComponent(GoBack))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackActionPerformed
        VectoresHome mnu= new VectoresHome();
        mnu.show();
        dispose();        
    }//GEN-LAST:event_GoBackActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        AXI.setText("");
        AYJ.setText("");
        AZK.setText("");
        GEscalar.setText("");
        RVector.setText("");
        RModulo.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed

    private void SolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolvedActionPerformed
        int DAXI = 0,DAYJ = 0,DAZK = 0,DGEscalar = 0;
        int RAI = 0,RAJ = 0,RAK = 0;
        double SMODULO = 0,RRMODULO=0;
        
        String RVectorM="";
        String RModulos="";
        
        DAXI=Integer.parseInt(AXI.getText());
        DAYJ=Integer.parseInt(AYJ.getText());
        DAZK=Integer.parseInt(AZK.getText());
        DGEscalar=Integer.parseInt(GEscalar.getText());
        
        RAI = (DAXI * DGEscalar);
        RAJ = (DAYJ * DGEscalar);
        RAK = (DAZK *DGEscalar );
        
        
        RVectorM="";
                
        if(RAI >= 0){
            RVectorM = DGEscalar+".V= "+"" + RAI + "i";
        }else{
            RVectorM = DGEscalar+".V= "+"" + RAI + "i";
        }
        if(RAJ >= 0){
            RVectorM += "+" + RAJ + "j";
        }else{
            RVectorM += "" + RAJ + "j";
        }
        if(RAK >= 0){
            RVectorM += "+" + RAK + "k";
        }else{
            RVectorM += "" + RAK + "k";
        }
        RVector.setText(RVectorM);
               
        SMODULO = Math.pow(RAI, DGEscalar)+ Math.pow(RAJ, DGEscalar)+ Math.pow(RAK, DGEscalar);                
        RRMODULO = Math.sqrt(SMODULO);
        
        RModulos="" + RRMODULO;       
        
        RModulo.setText(RModulos);
        
    }//GEN-LAST:event_SolvedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Multiplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multiplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel APanel;
    private javax.swing.JTextField AXI;
    private javax.swing.JTextField AYJ;
    private javax.swing.JTextField AZK;
    private javax.swing.JPanel BPanel;
    private javax.swing.JButton Clear;
    private javax.swing.JTextField GEscalar;
    private javax.swing.JPanel General;
    private javax.swing.JButton GoBack;
    private javax.swing.JLabel JLModulo;
    private javax.swing.JTextField RModulo;
    private javax.swing.JTextField RVector;
    private javax.swing.JButton Solved;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlAXI;
    private javax.swing.JLabel jlAYJ;
    private javax.swing.JLabel jlAZK;
    private javax.swing.JLabel jlEscalar;
    // End of variables declaration//GEN-END:variables
}
