package Producto;
/*
 * @author Hacktotopo
*/

public class ProductoMixto extends javax.swing.JFrame {

    /**
     * Creates new form ProductoCruz
     */
    public ProductoMixto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PGeneral = new javax.swing.JPanel();
        PanelValores = new javax.swing.JPanel();
        jTMUI = new javax.swing.JTextField();
        jTMUJ = new javax.swing.JTextField();
        jTMUK = new javax.swing.JTextField();
        jTMVI = new javax.swing.JTextField();
        jTMVJ = new javax.swing.JTextField();
        jTMVK = new javax.swing.JTextField();
        jTMWI = new javax.swing.JTextField();
        jTMWJ = new javax.swing.JTextField();
        jTMWK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btResolverPM = new javax.swing.JButton();
        JTRJ = new javax.swing.JTextField();
        JTRI = new javax.swing.JTextField();
        jTextResultadoMixto = new javax.swing.JTextField();
        JTRK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btRegresar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 170, 166));
        setPreferredSize(new java.awt.Dimension(550, 550));
        setResizable(false);

        PGeneral.setBackground(new java.awt.Color(44, 151, 222));
        PGeneral.setAutoscrolls(true);
        PGeneral.setPreferredSize(new java.awt.Dimension(550, 550));

        PanelValores.setBackground(new java.awt.Color(43, 43, 43));
        PanelValores.setPreferredSize(new java.awt.Dimension(540, 300));

        jTMUI.setBackground(new java.awt.Color(119, 120, 123));
        jTMUI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMUI.setForeground(new java.awt.Color(236, 240, 241));
        jTMUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMUIActionPerformed(evt);
            }
        });

        jTMUJ.setBackground(new java.awt.Color(119, 120, 123));
        jTMUJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMUJ.setForeground(new java.awt.Color(236, 240, 241));
        jTMUJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMUJActionPerformed(evt);
            }
        });

        jTMUK.setBackground(new java.awt.Color(119, 120, 123));
        jTMUK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMUK.setForeground(new java.awt.Color(236, 240, 241));
        jTMUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMUKActionPerformed(evt);
            }
        });

        jTMVI.setBackground(new java.awt.Color(119, 120, 123));
        jTMVI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMVI.setForeground(new java.awt.Color(236, 240, 241));
        jTMVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMVIActionPerformed(evt);
            }
        });

        jTMVJ.setBackground(new java.awt.Color(119, 120, 123));
        jTMVJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMVJ.setForeground(new java.awt.Color(236, 240, 241));
        jTMVJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMVJActionPerformed(evt);
            }
        });

        jTMVK.setBackground(new java.awt.Color(119, 120, 123));
        jTMVK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMVK.setForeground(new java.awt.Color(236, 240, 241));
        jTMVK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMVKActionPerformed(evt);
            }
        });

        jTMWI.setBackground(new java.awt.Color(119, 120, 123));
        jTMWI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMWI.setForeground(new java.awt.Color(236, 240, 241));
        jTMWI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMWIActionPerformed(evt);
            }
        });

        jTMWJ.setBackground(new java.awt.Color(119, 120, 123));
        jTMWJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMWJ.setForeground(new java.awt.Color(236, 240, 241));
        jTMWJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMWJActionPerformed(evt);
            }
        });

        jTMWK.setBackground(new java.awt.Color(119, 120, 123));
        jTMWK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTMWK.setForeground(new java.awt.Color(236, 240, 241));
        jTMWK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMWKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 196, 35));
        jLabel1.setText("I");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 196, 35));
        jLabel3.setText("J");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 196, 35));
        jLabel4.setText("K");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 196, 35));
        jLabel5.setText("I");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 196, 35));
        jLabel6.setText("J");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 196, 35));
        jLabel7.setText("K");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 196, 35));
        jLabel8.setText("I");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 196, 35));
        jLabel9.setText("J");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 196, 35));
        jLabel10.setText("K");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("U");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("V");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("w");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("(U V W)");

        javax.swing.GroupLayout PanelValoresLayout = new javax.swing.GroupLayout(PanelValores);
        PanelValores.setLayout(PanelValoresLayout);
        PanelValoresLayout.setHorizontalGroup(
            PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelValoresLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelValoresLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(PanelValoresLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5))
                    .addGroup(PanelValoresLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTMUI)
                    .addComponent(jTMVI)
                    .addComponent(jTMWI))
                .addGap(18, 18, 18)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTMVJ)
                    .addComponent(jTMUJ)
                    .addComponent(jTMWJ))
                .addGap(21, 21, 21)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTMVK)
                    .addComponent(jTMUK)
                    .addComponent(jTMWK))
                .addContainerGap())
            .addGroup(PanelValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelValoresLayout.setVerticalGroup(
            PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelValoresLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTMUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMUJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMUK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMVI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMVJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMVK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addGroup(PanelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMWI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMWJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTMWK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        btResolverPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Resolver.png"))); // NOI18N
        btResolverPM.setText("Resolver");
        btResolverPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResolverPMActionPerformed(evt);
            }
        });

        JTRJ.setBackground(new java.awt.Color(119, 120, 123));
        JTRJ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JTRJ.setForeground(new java.awt.Color(236, 240, 241));
        JTRJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTRJActionPerformed(evt);
            }
        });

        JTRI.setBackground(new java.awt.Color(119, 120, 123));
        JTRI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JTRI.setForeground(new java.awt.Color(236, 240, 241));
        JTRI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTRIActionPerformed(evt);
            }
        });

        jTextResultadoMixto.setEditable(false);
        jTextResultadoMixto.setBackground(new java.awt.Color(245, 80, 100));
        jTextResultadoMixto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextResultadoMixto.setForeground(new java.awt.Color(236, 240, 241));
        jTextResultadoMixto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextResultadoMixto.setText("RESULTADO");
        jTextResultadoMixto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextResultadoMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextResultadoMixtoActionPerformed(evt);
            }
        });

        JTRK.setBackground(new java.awt.Color(119, 120, 123));
        JTRK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JTRK.setForeground(new java.awt.Color(236, 240, 241));
        JTRK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTRKActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("PRODUCTO MIXTO");

        btRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Regresar.png"))); // NOI18N
        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Reducir.png"))); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PGeneralLayout = new javax.swing.GroupLayout(PGeneral);
        PGeneral.setLayout(PGeneralLayout);
        PGeneralLayout.setHorizontalGroup(
            PGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelValores, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PGeneralLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(JTRI, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(JTRJ, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JTRK, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(PGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btResolverPM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(PGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PGeneralLayout.createSequentialGroup()
                        .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRegresar)
                        .addContainerGap())
                    .addGroup(PGeneralLayout.createSequentialGroup()
                        .addComponent(jTextResultadoMixto)
                        .addGap(162, 162, 162))))
            .addGroup(PGeneralLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PGeneralLayout.setVerticalGroup(
            PGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(PanelValores, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTRI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTRJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTRK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jTextResultadoMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(PGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btResolverPM)
                    .addComponent(btLimpiar)
                    .addComponent(btRegresar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTMUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMUIActionPerformed

    private void jTMUJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMUJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMUJActionPerformed

    private void jTMUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMUKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMUKActionPerformed

    private void jTMVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMVIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMVIActionPerformed

    private void jTMVJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMVJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMVJActionPerformed

    private void jTMVKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMVKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMVKActionPerformed

    private void jTMWIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMWIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMWIActionPerformed

    private void jTMWJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMWJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMWJActionPerformed

    private void jTMWKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMWKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMWKActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        VectoresHome mnu= new VectoresHome();
        mnu.show();
        dispose();
    }//GEN-LAST:event_btRegresarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        jTMUI.setText("");
        jTMUJ.setText("");
        jTMUK.setText("");
        jTMVI.setText("");
        jTMVJ.setText("");
        jTMVK.setText("");
        jTMWI.setText("");
        jTMWJ.setText("");
        jTMWK.setText("");
        JTRI.setText("");
        JTRJ.setText("");
        JTRK.setText("");
        jTextResultadoMixto.setText("RESULTADO");
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btResolverPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResolverPMActionPerformed

        int PMU1 = 0, PMU2 = 0 , PMU3 = 0,PMV1 = 0, PMV2 = 0 , PMV3 = 0,PMW1 = 0, PMW2 = 0 , PMW3 = 0;
        int RMI = 0,RMJ = 0, RMK = 0;
        int UVM = 0, UVMI=0 ,UVMJ=0 , UVMK=0 ;

        String PMixtoI = "";
        String PMixtoJ = "";
        String PMixtoK = "";
        String PMixto = "";

        PMV1=Integer.parseInt(jTMVI.getText());
        PMV2=Integer.parseInt(jTMVJ.getText());
        PMV3=Integer.parseInt(jTMVK.getText());

        PMW1=Integer.parseInt(jTMWI.getText());
        PMW2=Integer.parseInt(jTMWJ.getText());
        PMW3=Integer.parseInt(jTMWK.getText());

        RMI = (PMV2 * PMW3) - (PMW2 * PMV3);
        RMJ = -((PMV1 * PMW3)-(PMW1 * PMV3));
        RMK = (PMV1 * PMW2)- (  PMW1 * PMV2);

        PMixtoI = "";
        PMixtoJ = "";
        PMixtoK = "";

        if(RMI >= 0){
            PMixtoI = "" + RMI;
        }else{
            PMixtoI = "" + RMI;
        }
        if(RMJ >= 0){
            PMixtoJ = "+" + RMJ;
        }else{
            PMixtoJ = "" + RMJ;
        }
        if(RMK >= 0){
            PMixtoK = "+" + RMK;
        }else{
            PMixtoK = "" + RMK;     }

        JTRI.setText(PMixtoI);
        JTRJ.setText(PMixtoJ);
        JTRK.setText(PMixtoK);

        PMU1=Integer.parseInt(jTMUI.getText());
        PMU2=Integer.parseInt(jTMUJ.getText());
        PMU3=Integer.parseInt(jTMUK.getText());

        UVMI=Integer.parseInt(JTRI.getText());
        UVMJ=Integer.parseInt(JTRJ.getText());
        UVMK=Integer.parseInt(JTRK.getText());

        PMixto = "";
        UVM = ((PMU1 * UVMI)+(PMU2 * UVMJ)+(PMU3 * UVMK));
        PMixto = ""+UVM;
        jTextResultadoMixto.setText(PMixto);
    }//GEN-LAST:event_btResolverPMActionPerformed

    private void jTextResultadoMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextResultadoMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextResultadoMixtoActionPerformed

    private void JTRKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTRKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTRKActionPerformed

    private void JTRJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTRJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTRJActionPerformed

    private void JTRIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTRIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTRIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoMixto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTRI;
    private javax.swing.JTextField JTRJ;
    private javax.swing.JTextField JTRK;
    private javax.swing.JPanel PGeneral;
    private javax.swing.JPanel PanelValores;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btResolverPM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTMUI;
    private javax.swing.JTextField jTMUJ;
    private javax.swing.JTextField jTMUK;
    private javax.swing.JTextField jTMVI;
    private javax.swing.JTextField jTMVJ;
    private javax.swing.JTextField jTMVK;
    private javax.swing.JTextField jTMWI;
    private javax.swing.JTextField jTMWJ;
    private javax.swing.JTextField jTMWK;
    private javax.swing.JTextField jTextResultadoMixto;
    // End of variables declaration//GEN-END:variables
}
